### ISSUE TITLE
Is it possible to hide the value?

### ISSUE THREAD

**Issue by melat0nin** [benjypng/logseq-sliders-plugin#1]
This is a great plugin, thanks for creating it!

I wondered if it's possible to hide the value, so only the slider is displayed? I'm using them as progress bars for work, and the visual indicator is enough without the value displayed below (though of course that should be stored, for queries).

Is this possible?

**Comment by benjypng** [comment]
This is available in 1.0.1.
Head on to the plugin settings to turn it on.
