### ISSUE TITLE
Inline slider

### ISSUE THREAD

**Issue by AkimboJones** [benjypng/logseq-sliders-plugin#2]
Great plugin. Was wondering if there was a way to render the slider so it does not break the line:

What currently occurs:
![Screen Shot 2022-04-25 at 11 25 28 am](https://user-images.githubusercontent.com/102349875/165015834-b087e921-890d-4f38-adb8-d0caeab4b842.png)
Given the following block entry:
![Screen Shot 2022-04-25 at 11 25 37 am](https://user-images.githubusercontent.com/102349875/165015847-0866e7c9-c3d4-4f8b-bf51-9cee48d15401.png)

**What could be a feature is to render the slider in line.** I'm not that savvy with coding or html, so i'm not too sure if there was already a way to do that by modifying the "div" tag. :)

![Screen Shot 2022-04-25 at 11 32 49 am](https://user-images.githubusercontent.com/102349875/165016415-22e0433e-849d-4a47-8d6f-763d74e91862.png)

Thanks.

**Comment by benjypng** [comment]
Fixed in v1.0.2.
