### ISSUE TITLE
Sliders don't persist

### ISSUE THREAD

**Issue by melat0nin** [benjypng/logseq-sliders-plugin#3]
I'm finding that my sliders don't persist over time -- when I create them, a couple of days later i see e.g. this:

![image](https://user-images.githubusercontent.com/912688/165924469-8c093951-c52e-48d3-9730-9db4abea56c6.png)

instead of the actual slider. The content of that block is this:

```
[:span {:is "slider-uerfpdbe"}100]
value:: 60
```

To fix this I basically have to delete the first line and re-insert it, which is time-consuming of course.

For reference, in this case I have used block refs to display the same block elsewhere on the page (a table showing progress of multiple sliders). Perhaps that has something to do with it?

**Comment by benjypng** [comment]
Apologies. Fixed in 1.0.3.
