### ISSUE TITLE
When reindex, the value of slider changed.

### ISSUE THREAD

**Issue by mzwlevi** [benjypng/logseq-sliders-plugin#4]
https://user-images.githubusercontent.com/78029539/167460383-5968f0dd-a59a-4bc0-a2b0-af89c729e518.mov

**Comment by benjypng** [comment]
What version of Logseq are you currently using?

**Comment by mzwlevi** [comment]
> What version of Logseq are you currently using?

0.6.7, now I am using 0.6.8, this issue can be reproduced.

**Comment by benjypng** [comment]
Yes, it's a Logseq bug that has not been fixed yet. Have notified the team a few days ago. Will update here when it has.

**Comment by mzwlevi** [comment]
> Yes, it's a Logseq bug that has not been fixed yet. Have notified the team a few days ago. Will update here when it has.

👌

**Comment by benjypng** [comment]
This has been fixed in v1.1.2.
