### ISSUE TITLE
Not working for me?

### ISSUE THREAD

**Issue by richd67** [benjypng/logseq-sliders-plugin#5]
Tried it and nothing 
This is the text produced {{renderer :slider_mmlduznyl}} [:span {:is "slider-mmlduznyl"}] but it doesnt render anything?

**Comment by benjypng** [comment]
Apologies! Please try the latest version.

**Comment by benjypng** [comment]
Fixed in the latest version. Refer to [https://github.com/benjypng/logseq-sliders-plugin?tab=readme-ov-file#usage](https://github.com/benjypng/logseq-sliders-plugin?tab=readme-ov-file#usage).
