### ISSUE TITLE
How to set min/max range

### ISSUE THREAD

**Issue by rohitshetty** [benjypng/logseq-sliders-plugin#6]
Hi!
Thank you for this plugin. 

I want to set min/max value available - what changes should I do to the markup to enable this?

**Comment by benjypng** [comment]
Fixed in the latest version. Refer to [https://github.com/benjypng/logseq-sliders-plugin?tab=readme-ov-file#usage](https://github.com/benjypng/logseq-sliders-plugin?tab=readme-ov-file#usage).
