### ISSUE TITLE
Adding [:div {:is "slider-jlvafjj"}50] at the end does not work.

### ISSUE THREAD

**Issue by msjsc001** [benjypng/logseq-sliders-plugin#7]
Adding [:div {:is "slider-jlvafjj"}50] at the end does not work.
![image](https://github.com/hkgnp/logseq-sliders-plugin/assets/93178788/e64c0373-0ac5-45f1-b3bc-9f4dfb4e4691)
![image](https://github.com/hkgnp/logseq-sliders-plugin/assets/93178788/26830231-e63e-49b1-9a85-3a0e4ab96cb7)

**Comment by benjypng** [comment]
This is fixed in the latest version. Refer to [https://github.com/benjypng/logseq-sliders-plugin?tab=readme-ov-file#usage](https://github.com/benjypng/logseq-sliders-plugin?tab=readme-ov-file#usage).
